#!/usr/bin/env python3
"""
curate_by_tag_map.py — Extrae versiones curadas de un archivo mezclado.

Lee un tag map CSV (sección -> líneas -> compañías) y produce una versión
del archivo fuente para cada compañía especificada, conteniendo solo las
secciones tageadas para esa compañía.

Uso:
    python scripts/curate_by_tag_map.py \\
        --source memoria_ALex.md \\
        --tag-map docs/migrations/TAG_MAP_memoria_ALex.csv \\
        --output-dir docs/migrations/curated/ \\
        --prefix MEMORIA \\
        --companies Pinnacle,InvestorOS,GeoCarpentry

Para cada compañía produce un archivo `<PREFIX>_<COMPANY>.md` con header
indicando la procedencia y las secciones extraídas.

NO sanitiza secretos. Pasar el output por el sanitizador después.
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path


COMPANY_NORMALIZE = {
    "pinnacle": "Pinnacle",
    "investoros": "InvestorOS",
    "geo": "GeoCarpentry",
    "geocarpentry": "GeoCarpentry",
    "geo-carpentry": "GeoCarpentry",
    "compartido": "Compartido",
    "shared": "Compartido",
}


def normalize(tag: str) -> str:
    return COMPANY_NORMALIZE.get(tag.strip().lower(), tag.strip())


def parse_companies_cell(cell: str) -> set[str]:
    """Parses 'Pinnacle;InvestorOS' or 'Pinnacle' -> set of normalized tags."""
    if not cell:
        return set()
    return {normalize(t) for t in cell.split(";") if t.strip()}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, type=Path, help="Archivo fuente (.md)")
    parser.add_argument("--tag-map", required=True, type=Path, help="CSV tag map")
    parser.add_argument("--output-dir", required=True, type=Path, help="Carpeta destino")
    parser.add_argument("--prefix", required=True, help="Prefijo para output files (ej. MEMORIA -> INVESTOROS_MEMORIA.md)")
    parser.add_argument(
        "--companies",
        default="Pinnacle,InvestorOS,GeoCarpentry",
        help="Lista CSV de compañías destino. Compartido se añade automáticamente a cada output.",
    )
    parser.add_argument("--include-shared", action="store_true", default=True, help="(default: True) incluir secciones Compartido en cada output")
    args = parser.parse_args()

    if not args.source.exists():
        print(f"ERROR: source not found: {args.source}", file=sys.stderr)
        return 2
    if not args.tag_map.exists():
        print(f"ERROR: tag map not found: {args.tag_map}", file=sys.stderr)
        return 2

    args.output_dir.mkdir(parents=True, exist_ok=True)

    # Read source as lines (preserve original line content)
    with args.source.open("r", encoding="utf-8") as f:
        source_lines = f.read().splitlines(keepends=True)
    total_lines = len(source_lines)

    # Read tag map
    sections: list[dict] = []
    with args.tag_map.open("r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        for row in reader:
            try:
                start = int(row["start_line"])
                end = int(row["end_line"])
            except (KeyError, ValueError):
                print(f"WARN: skipping row with bad line numbers: {row}", file=sys.stderr)
                continue
            sections.append({
                "id": row.get("section_id", ""),
                "start": start,
                "end": end,
                "heading": row.get("heading", "").strip('"'),
                "companies": parse_companies_cell(row.get("companies", "")),
                "confidence": row.get("confidence", ""),
                "note": row.get("note", ""),
            })

    print(f"Source: {args.source} ({total_lines} lines)")
    print(f"Tag map: {args.tag_map} ({len(sections)} sections)")

    targets = [normalize(c) for c in args.companies.split(",") if c.strip()]

    summary: dict[str, dict] = {}

    for company in targets:
        out_path = args.output_dir / f"{company.upper()}_{args.prefix}.md"
        with out_path.open("w", encoding="utf-8") as out:
            out.write(f"# {company} — {args.prefix} (curated)\n\n")
            out.write(f"> Auto-generated by `scripts/curate_by_tag_map.py` from `{args.source.name}`\n")
            out.write(f"> Tag map: `{args.tag_map.name}`\n")
            out.write(f"> Sections included: tagged `{company}` and/or `Compartido`\n\n")
            out.write("---\n\n")

            included_count = 0
            included_lines = 0
            for sec in sections:
                if company in sec["companies"] or (args.include_shared and "Compartido" in sec["companies"]):
                    out.write(f"<!-- section {sec['id']} | lines {sec['start']}-{sec['end']} | tags: {';'.join(sorted(sec['companies']))} | conf:{sec['confidence']} -->\n")
                    # Lines are 1-indexed in tag map, 0-indexed in array
                    start_idx = max(0, sec["start"] - 1)
                    end_idx = min(total_lines, sec["end"])
                    chunk = source_lines[start_idx:end_idx]
                    out.writelines(chunk)
                    if not chunk or not chunk[-1].endswith("\n"):
                        out.write("\n")
                    out.write("\n")
                    included_count += 1
                    included_lines += (end_idx - start_idx)

        summary[company] = {
            "path": out_path,
            "sections": included_count,
            "lines": included_lines,
        }
        print(f"  -> {out_path}: {included_count} sections, {included_lines} lines")

    print()
    print("Summary:")
    total_in = sum(s["lines"] for s in summary.values())
    print(f"  Source lines: {total_lines}")
    print(f"  Total output lines (with overlap from Compartido): {total_in}")
    print(f"  Ratio (output/source): {total_in/total_lines:.2f}x  (>1.0 means Compartido sections duplicated; <1.0 means content lost)")

    return 0


if __name__ == "__main__":
    sys.exit(main())
